spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
#  file:
#    path: ./
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG




